baseURL = 'https://kemxr.github.io/labveilletech/'
languageCode = 'en-us'
title = 'Marc Bouriot'
theme = 'rusty-typewriter-main'

enableRobotsTXT = true

# rtwt = Rusty Typewriter Theme
[params.rtwt.side.home]
taxonomies = ['tags', 'topics']
countTaxonomy = 3

[taxonomies]
tag = 'tags'
topic = 'topics'

[params.author]
name = 'Marc Bouriot'

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 1

[[menus.main]]
name = 'About'
pageRef = '/about.md'
weight = 3

# build search index ================
[outputFormats]
 [outputFormats.SearchIndex]
  mediaType = "application/json"
  baseName = "searchindex"
  isPlainText = true
  notAlternative = true

[mediaTypes]
 [mediaTypes."application/json"]
  suffixes = ["json"]

[outputs]
 home = ["HTML","RSS","SearchIndex"]
# ===================================
